const sampleData = {
    1: [
      {
        id: "1",
        description: "Dominoes",
        category: "FoodNDinning",
        date: "2020-01-02",
        amount: 430,
      },
      {
        id: "2",
        description: "Car wash",
        category: "utility",
        date: "2020-01-06",
        amount: 500,
      },
      {
        id: "3",
        description: "Amazon",
        category: "shopping",
        date: "2020-01-07",
        amount: 2030,
      },
      {
        id: "4",
        description: "House rent",
        category: "FoodNDinning",
        date: "2020-01-03",
        amount: 35900,
      },
      {
        id: "5",
        description: "Tuition",
        category: "education",
        date: "2020-01-12",
        amount: 2200,
      },
      {
        id: "6",
        description: "Laundry",
        category: "Personal Care",
        date: "2020-01-14",
        amount: 320,
      },
      {
        id: "7",
        description: "Vacation",
        category: "Travel",
        date: "2020-01-18",
        amount: 3430,
      },
      {
        id: "8",
        description: "Vacation",
        category: "Travel",
        date: "2020-01-25",
        amount: 2050,
      },
    ],
    2: [
      {
        id: "1",
        description: "Dominoes",
        category: "FoodNDining",
        date: "2020-02-02",
        amount: 560,
      },
      {
        id: "2",
        description: "Car wash",
        category: "utility",
        date: "2020-02-06",
        amount: 590,
      },
      {
        id: "3",
        description: "Tuition",
        category: "education",
        date: "2020-02-12",
        amount: 2250,
      },
      {
        id: "4",
        description: "Dominoes",
        category: "FoodNDining",
        date: "2020-02-02",
        amount: 560,
      },
      {
        id: "5",
        description: "Amazon",
        category: "shopping",
        date: "2020-02-07",
        amount: 3030,
      },
      {
        id: "6",
        description: "Laundry",
        category: "Personal Care",
        date: "2020-02-14",
        amount: 620,
      },
      {
        id: "7",
        description: "Vacation",
        category: "Travel",
        date: "2020-02-18",
        amount: 1430,
      },
    ],
    3: [
      {
        id: "1",
        description: "Dominoes",
        category: "FoodNDining",
        date: "2020-03-02",
        amount: 470,
      },
      {
        id: "2",
        description: "Car wash",
        category: "utility",
        date: "2020-03-06",
        amount: 540,
      },
      {
        id: "3",
        description: "Vacation",
        category: "Travel",
        date: "2020-03-18",
        amount: 1430,
      },
      {
        id: "4",
        description: "House rent",
        category: "FoodNDinning",
        date: "2020-03-03",
        amount: 35900,
      },
      {
        id: "5",
        description: "Tuition",
        category: "education",
        date: "2020-03-12",
        amount: 5200,
      },
      {
        id: "6",
        description: "Laundry",
        category: "Personal Care",
        date: "2020-03-14",
        amount: 520,
      },
    ],
    4: [
      {
        id: "1",
        description: "Amazon",
        category: "shopping",
        date: "2020-04-07",
        amount: 2030,
      },
      {
        id: "2",
        description: "Car wash",
        category: "utility",
        date: "2020-04-06",
        amount: 560,
      },
      {
        id: "3",
        description: "Dominoes",
        category: "FoodNDining",
        date: "2020-04-02",
        amount: 430,
      },
      {
        id: "4",
        description: "House rent",
        category: "FoodNDinning",
        date: "2020-04-03",
        amount: 35900,
      },
      {
        id: "5",
        description: "Tuition",
        category: "education",
        date: "2020-04-12",
        amount: 2200,
      },
      {
        id: "6",
        description: "Laundry",
        category: "Personal Care",
        date: "2020-04-14",
        amount: 320,
      },
    ],
    5: [
      {
        id: "1",
        description: "Dominoes",
        category: "FoodNDining",
        date: "2020-05-02",
        amount: 430,
      },
      {
        id: "2",
        description: "Car wash",
        category: "utility",
        date: "2020-05-06",
        amount: 700,
      },
      {
        id: "3",
        description: "Amazon",
        category: "shopping",
        date: "2020-05-07",
        amount: 1030,
      },
      {
        id: "4",
        description: "House rent",
        category: "FoodNDinning",
        date: "2020-05-03",
        amount: 35900,
      },
      {
        id: "5",
        description: "Tuition",
        category: "education",
        date: "2020-05-12",
        amount: 2200,
      },
      {
        id: "6",
        description: "Laundry",
        category: "Personal Care",
        date: "2020-05-14",
        amount: 322,
      },
      {
        id: "7",
        description: "Vacation",
        category: "Travel",
        date: "2020-05-18",
        amount: 3430,
      },
    ],
    6: [
      {
        id: "1",
        description: "Dominoes",
        category: "FoodNDining",
        date: "2020-06-02",
        amount: 330,
      },
      {
        id: "2",
        description: "Car wash",
        category: "utility",
        date: "2020-06-06",
        amount: 530,
      },
      {
        id: "3",
        description: "Amazon",
        category: "shopping",
        date: "2020-06-07",
        amount: 2130,
      },
      {
        id: "4",
        description: "House rent",
        category: "FoodNDinning",
        date: "2020-06-03",
        amount: 35900,
      },
      {
        id: "5",
        description: "Tuition",
        category: "education",
        date: "2020-06-12",
        amount: 2290,
      },
      {
        id: "6",
        description: "Laundry",
        category: "Personal Care",
        date: "2020-06-14",
        amount: 620,
      },
      {
        id: "7",
        description: "House rent",
        category: "FoodNDinning",
        date: "2020-06-03",
        amount: 35900,
      },
    ],
    7: [
      {
        id: "1",
        description: "Car wash",
        category: "utility",
        date: "2020-07-06",
        amount: 500,
      },
      {
        id: "2",
        description: "Dominoes",
        category: "FoodNDining",
        date: "2020-07-02",
        amount: 430,
      },
      {
        id: "3",
        description: "Amazon",
        category: "shopping",
        date: "2020-07-07",
        amount: 2030,
      },
      {
        id: "4",
        description: "Tuition",
        category: "education",
        date: "2020-07-12",
        amount: 2200,
      },
      {
        id: "5",
        description: "House rent",
        category: "FoodNDinning",
        date: "2020-07-03",
        amount: 36900,
      },
      {
        id: "6",
        description: "Laundry",
        category: "Personal Care",
        date: "2020-07-14",
        amount: 320,
      },
      {
        id: "7",
        description: "Vacation",
        category: "Travel",
        date: "2020-07-18",
        amount: 3430,
      },
    ],
    8: [
      {
        id: "1",
        description: "Dominoes",
        category: "FoodNDining",
        date: "2020-08-02",
        amount: 430,
      },
      {
        id: "2",
        description: "Car wash",
        category: "utility",
        date: "2020-08-06",
        amount: 300,
      },
      {
        id: "3",
        description: "Amazon",
        category: "shopping",
        date: "2020-08-07",
        amount: 2630,
      },
      {
        id: "4",
        description: "House rent",
        category: "FoodNDinning",
        date: "2020-08-03",
        amount: 35960,
      },
      {
        id: "5",
        description: "Tuition",
        category: "education",
        date: "2020-08-12",
        amount: 2200,
      },
      {
        id: "6",
        description: "Laundry",
        category: "Personal Care",
        date: "2020-08-14",
        amount: 320,
      },
      {
        id: "7",
        description: "Vacation",
        category: "Travel",
        date: "2020-08-18",
        amount: 3430,
      },
    ],
    9: [
      {
        id: "1",
        description: "Amazon",
        category: "shopping",
        date: "2020-09-07",
        amount: 2030,
      },
      {
        id: "2",
        description: "Tuition",
        category: "education",
        date: "2020-09-12",
        amount: 2560,
      },
      {
        id: "3",
        description: "Dominoes",
        category: "FoodNDining",
        date: "2020-09-02",
        amount: 430,
      },
      {
        id: "4",
        description: "House rent",
        category: "FoodNDinning",
        date: "2020-09-03",
        amount: 35900,
      },
      {
        id: "5",
        description: "Car wash",
        category: "utility",
        date: "2020-09-06",
        amount: 500,
      },
      {
        id: "6",
        description: "Laundry",
        category: "Personal Care",
        date: "2020-09-14",
        amount: 320,
      },
      {
        id: "7",
        description: "Vacation",
        category: "Travel",
        date: "2020-09-18",
        amount: 3430,
      },
    ],
    10: [
      {
        id: "1",
        description: "Dominoes",
        category: "FoodNDining",
        date: "2020-10-02",
        amount: 130,
      },
      {
        id: "2",
        description: "Car wash",
        category: "utility",
        date: "2020-10-06",
        amount: 580,
      },
      {
        id: "3",
        description: "Amazon",
        category: "shopping",
        date: "2020-10-07",
        amount: 2030,
      },
      {
        id: "4",
        description: "House rent",
        category: "FoodNDinning",
        date: "2020-10-03",
        amount: 35900,
      },
      {
        id: "5",
        description: "Tuition",
        category: "education",
        date: "2020-10-12",
        amount: 2200,
      },
      {
        id: "6",
        description: "Laundry",
        category: "Personal Care",
        date: "2020-10-14",
        amount: 320,
      },
      {
        id: "7",
        description: "Vacation",
        category: "Travel",
        date: "2020-10-18",
        amount: 3430,
      },
    ],
    11: [
      {
        id: "1",
        description: "Dominoes",
        category: "FoodNDining",
        date: "2020-11-02",
        amount: 430,
      },
      {
        id: "2",
        description: "Car wash",
        category: "utility",
        date: "2020-11-06",
        amount: 500,
      },
      {
        id: "3",
        description: "Amazon",
        category: "shopping",
        date: "2020-11-07",
        amount: 2030,
      },
      {
        id: "4",
        description: "House rent",
        category: "FoodNDinning",
        date: "2020-11-03",
        amount: 35900,
      },
      {
        id: "5",
        description: "Tuition",
        category: "education",
        date: "2020-11-12",
        amount: 2200,
      },
      {
        id: "6",
        description: "Laundry",
        category: "Personal Care",
        date: "2020-11-14",
        amount: 720,
      },
      {
        id: "7",
        description: "Vacation",
        category: "Travel",
        date: "2020-11-18",
        amount: 3430,
      },
    ],
    12: [
      {
        id: "1",
        description: "Laundry",
        category: "Personal Care",
        date: "2020-12-14",
        amount: 320,
      },
      {
        id: "2",
        description: "House rent",
        category: "FoodNDinning",
        date: "2020-12-03",
        amount: 35900,
      },
      {
        id: "3",
        description: "Amazon",
        category: "shopping",
        date: "2020-12-07",
        amount: 1738,
      },
      {
        id: "4",
        description: "Car wash",
        category: "utility",
        date: "2020-12-06",
        amount: 500,
      },
      {
        id: "5",
        description: "Tuition",
        category: "education",
        date: "2020-12-12",
        amount: 2200,
      },
      {
        id: "6",
        description: "Dominoes",
        category: "FoodNDining",
        date: "2020-12-02",
        amount: 430,
      },
      {
        id: "7",
        description: "Vacation",
        category: "Travel",
        date: "2020-12-18",
        amount: 3430,
      },
    ],
  };
  
  export default sampleData;
  